[project]
name = "server"
version = "0.1.0"
description = "A simple MCP server with FastAPI integration"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.6.0",
]
[project.scripts]
start = "server:run"
